version: "3.8"
services:
  mysql:
    container_name: mysql
    build: ./db
    ports:
    - target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: dbvol
      target: /var/lib/mysql

  flask-app:
    container_name: flask-app 
    build: ./flask-app
    ports:
    - target: 5000
      protocol: tcp
    depends_on:
    - "mysql"
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - "flask-app"
    - "mysql"

volumes:
  dbvol: