version: "3.8"
services:
  mysql:
    container_name: mysql
    image: arichards98/trio-mysql:latest
    #build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask-db
    ports:
    - target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: dbvol
      target: /var/lib/mysql

  flask-app:
    container_name: flask-app
    image: arichards98/trio-flask-app:latest 
    #build: ./flask-app
    environment:
      DATABASE_URI: 'mysql+pymysql://root:root@mysql:3306/flask-db'
    ports:
    - target: 5000
      protocol: tcp
    depends_on:
    - "mysql"
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - "flask-app"
    - "mysql"

volumes:
  dbvol: